### ISSUE TITLE
Latency when browsing

### ISSUE THREAD

**Issue by jonaswindey** [luisrudge/next.js-auth0#6]
When visiting https://nextjs-auth0.now.sh/ and clicking on "Sign in" there's a latency of +- 3 seconds before the page is loaded. 

The content downloaded from https://nextjs-auth0.now.sh/auth/sign-in.json is 691KB. Is the version online a production build or the dev build?

**Comment by luisrudge** [comment]
Hi, thanks for opening this issue. This is a known issue to next.js The problem is described [here](https://github.com/zeit/next.js/issues/118). The problem is that the Auth0Lock dependency is huge, and we're loading that when you fetch the sign in page. The problem is upstream, though. Nothing we can do here. 😭  I could probably load lock from the cdn, but that's a super hack :(

What do you think?

**Comment by nmaro** [comment]
Does it work now that that issue has been fixed?

**Comment by luisrudge** [comment]
@nmaro I'll try with the new version

**Comment by luisrudge** [comment]
I just updated the packages (already pushed and deployed). It still doesn't fix the issue because the auth0 dependency is not shared, so it's not being downloaded as a common chunk. We'll have to wait until https://github.com/zeit/next.js/pull/375 lands

**Comment by rajaraodv** [comment]
@luisrudge looks like zeit/next.js#375 is in. What needs to be done to get this working?

**Comment by luisrudge** [comment]
It needs to use the prefetch link
